root: true
parser: babel-eslint
plugins:
  - flowtype
  - prettier
extends:
  - airbnb
  - plugin:flowtype/recommended
  - prettier
  - prettier/flowtype
  - prettier/react
rules:
  no-shadow: off
  no-underscore-dangle: off
  import/extensions: off
  import/prefer-default-export: off
  react/default-props-match-prop-types: off
  react/destructuring-assignment: off
  react/no-array-index-key: warn
  react/no-unescaped-entities: off
  react/prop-types: warn
  react/sort-comp: off
  react/jsx-filename-extension: off
  jsx-a11y/anchor-has-content: off
  jsx-a11y/anchor-is-valid: off
  jsx-a11y/heading-has-content: off
  jsx-a11y/label-has-for: off
  prettier/prettier: error

overrides:
  - files:
      - "flow-typed/**/*.js"
    rules:
      flowtype/no-types-missing-file-annotation: off
  - files:
      - "**/*.test.js"
      - "**/__tests__/**/*.js"
    env:
      jest: true
